baseURL = "http://carrierennolds.com/"
languageCode = "en-us"
title = "Carrie Rennolds"

[params]
  subtitle = "Carrie, like the movie."
  content-background = "cornsilk"
  custom_css = ["css/artist-baltimore-main.css", 
                "css/illustration-instruction-margins.css", 
                "css/fake-new-yorker-header.css",
                "css/necroprancer-borders.css",
                "css/illustration-pedagogy-flex.css"]
  icon = "images/tampon-artists-rendering.png"

[menu]
  [[menu.main]]
    identifier = "sybil"
    name = "Sybil Press"
    pre = "<img class=tiny-icon src=/images/sybil-press-logo.jpg></img>"
    url = "http://www.sybilpress.org/"
    weight = 1
  [[menu.main]]
    name = "Fake New Yorker Volume 1"
    parent="sybil"
    url = "http://www.sybilpress.org/bookstore/fake-new-yorker-vol-2-2018-2nd-printing"
    weight = 2
  [[menu.main]]
    name = "Fake New Yorker Volume 2"
    parent="sybil"
    url = "http://www.sybilpress.org/bookstore/fake-new-yorker-vol-2-1st-edition"
    weight = 3