baseURL = "http://carrierennolds.com/"
languageCode = "en-us"
title = "Carrie Rennolds"

[params]
  subtitle = "Carrie, like the movie."
  custom_css = ["css/artist-baltimore-main.css", "css/illustration-instruction-margins.css", "css/fake-new-yorker-header.css"]
  icon = "images/tampon-artists-rendering.png"
